apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-streaming
  template:
    metadata:
      labels:
        app: spark-streaming
    spec:
      containers:
        - name: spark
          image: datavizyon/spark-streaming:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka:9092"
            - name: KAFKA_TOPIC
              value: "transactions"
            - name: NESSIE_URI
              value: "http://nessie.default.svc.cluster.local:19120/api/v2"
            - name: WAREHOUSE
              value: "s3://lakehouse/"
            - name: MINIO_ENDPOINT
              value: "http://minio.default.svc.cluster.local:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "200m"
